### ISSUE TITLE
Output cuts off when encountering a warning in the dependency list

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [forrestthewoods/fts_depends#1]
The tool cuts off its output when it encounters a warning in the dependency list:
```
PS E:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition> fts_depends SkyrimSE.exe
+----------------------------------------------------------------------------------------------+---------------------------------+
| Dependency                                                                                   | Resolved Location (best guess)  |
+----------------------------------------------------------------------------------------------+---------------------------------+
| SkyrimSE.exe                                                                                 | SkyrimSE.exe                    |
| bink2w64.dll                                                                                 | bink2w64.dll                    |
| winhttp.dll                                                                                  | winhttp.dll                     |
| tbbmalloc.dll                                                                                | tbbmalloc.dll                   |
| vcruntime140.dll                                                                             | C:\Python310\vcruntime140.dll   |
| tbb.dll                                                                                      | tbb.dll                         |
| vcruntime140_1.dll                                                                           | C:\Python310\vcruntime140_1.dll |
| steam_api64.dll                                                                              | steam_api64.dll                 |
| d3dx9_42.dll                                                                                 | d3dx9_42.dll                    |
| LINK : warning LNK4078: multiple '.text' sections found with different attributes (C0000040) | ⚠️ Not Found ⚠️                   |
+----------------------------------------------------------------------------------------------+---------------------------------+
```
Here's the output from dumpbin:
```
E:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition>dumpbin.exe /DEPENDENTS SkyrimSE.exe
Microsoft (R) COFF/PE Dumper Version 14.34.31921.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file SkyrimSE.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    KERNEL32.dll
    USER32.dll
    ADVAPI32.dll
    SHELL32.dll
    ole32.dll
    X3DAudio1_7.dll
    XINPUT1_3.dll
    DINPUT8.dll
    WS2_32.dll
    bink2w64.dll
    WINHTTP.dll
    IPHLPAPI.DLL
    steam_api64.dll
    MSVCP140.dll
    SETUPAPI.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    d3dx9_42.dll
    d3d11.dll
    HID.DLL
    WINMM.dll
    dxgi.dll
    GDI32.dll
    OLEAUT32.dll
LINK : warning LNK4078: multiple '.text' sections found with different attributes (C0000040)

  Summary

     16EF000 .data
      14B000 .pdata
      841000 .rdata
       54000 .reloc
       93000 .rsrc
        2000 .text
     1601000 .text
        1000 _RDATA

```
Here's the relevant [game](https://store.steampowered.com/app/489830/The_Elder_Scrolls_V_Skyrim_Special_Edition/).

Have you considered parsing an executable's dependencies by hand? It would drop the dependency on dumpbin and the output would be a lot easier to work with.

**Comment by forrestthewoods** [comment]
Ah interesting. Yeah the problem with text parsing is it's impossible to know all the error conditions!

I've definitely thought about manually parsing to avoid dumpbin. However I know literally nothing about the file format. This was a very quick project. If you can point me towards a specification or a library (in any language) that manually parses I'll consider it. But I'm only likely to make a change if it's relatively low-effort.

**Comment by Ryan-rsm-McKenzie** [comment]
Here's a visual reference for the format: http://www.openrce.org/reference_library/files/reference/PE%20Format.pdf
Basically you use [`LoadLibraryEx`](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw) to map the image into your address space, and then you want to enumerate the import table to find all dlls that will be loaded. The you locate the dlls and restart the whole process. The biggest issue is that `which` uses a different search order than `LoadLibrary`, so you'll end up finding the wrong dlls using `which`.

**Comment by forrestthewoods** [comment]
Updated repo, releases, and cargo with a new build that should handle the LINK issue. I don't have SkyrimSE.exe so I can't test if there's another problem. I'm going to close this issue, re-open if you find another exe or dll that isn't processed right.

It looks like `LoadLibraryEx` can be given the flag `LOAD_LIBRARY_AS_DATAFILE` which could allow the extraction of dependencies without using dumpbin. That's an interesting project but if I'm being honest it's low on my hobby project priority list. I'll think about it though.
